### ISSUE TITLE
Not compatible with Flutter 3.22.0

### ISSUE THREAD

**Issue by xVemu** [bancolombia/dart-code-linter#126]
<details>

<summary>Crash log from Android Studio</summary>

## Dart analysis issue

Invalid argument (uri): URI scheme 'c' is not supported. Allowed schemes are 'file', 'dart-macro+file'.: "c:/Users/kkras/StudioProjects/bramkarz/lib/main.dart"

## Version information

- Dart SDK 3.4.3
- Dart IntelliJ 241.17502
- Android Studio Koala | 2024.1.1
- Windows 10 10.0

## Details

Invalid argument (uri): URI scheme 'c' is not supported. Allowed schemes are 'file', 'dart-macro+file'.: "c:/Users/kkras/StudioProjects/bramkarz/lib/main.dart"

```
#0      _VirtualFileClientUriConverter.fromClientUri (package:analyzer_plugin/src/utilities/client_uri_converter.dart:106:7)
#1      _VirtualFileClientUriConverter.fromClientFilePath (package:analyzer_plugin/src/utilities/client_uri_converter.dart:91:7)
#2      new Location.fromJson (package:analyzer_plugin/protocol/protocol_common.dart:2801:35)
#3      new AnalysisError.fromJson (package:analyzer_plugin/protocol/protocol_common.dart:155:29)
#4      new AnalysisErrorsParams.fromJson.<anonymous closure> (package:analyzer_plugin/protocol/protocol_generated.dart:122:31)
#5      JsonDecoder.decodeList (package:analyzer_plugin/src/protocol/protocol_internal.dart:347:27)
#6      new AnalysisErrorsParams.fromJson (package:analyzer_plugin/protocol/protocol_generated.dart:118:30)
#7      new AnalysisErrorsParams.fromNotification (package:analyzer_plugin/protocol/protocol_generated.dart:133:33)
#8      AbstractNotificationManager.handlePluginNotification (package:analysis_server/src/plugin/notification_manager.dart:85:50)
#9      PluginSession.handleNotification (package:analysis_server/src/plugin/plugin_manager.dart:868:10)
#10     ServerIsolateChannel.listen.<anonymous closure> (package:analyzer_plugin/src/channel/isolate_channel.dart:235:25)
#11     _rootRunUnary (dart:async/zone.dart:1415:13)
#12     _CustomZone.runUnary (dart:async/zone.dart:1308:19)
#13     _CustomZone.runUnaryGuarded (dart:async/zone.dart:1217:7)
#14     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:365:11)
#15     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:297:7)
#16     _SyncStreamControllerDispatch._sendData (dart:async/stream_controller.dart:784:19)
#17     _StreamController._add (dart:async/stream_controller.dart:658:7)
#18     _StreamController.add (dart:async/stream_controller.dart:606:5)
#19     _RawReceivePort._handleMessage (dart:isolate-patch/isolate_patch.dart:184:12)
```

## Debug log

```
1718694229763 => {"id":"102","method":"analysis.updateContent","params":{"files":{"file:///C:/Users/kkras/StudioProjects/bramkarz/lib/main.dart":{"type":"remove"}}},"clientRequestTime":1718694229763}
1718694229772 => {"id":"103","method":"analysis.updateContent","params":{"files":{"file:///C:/Users/kkras/StudioProjects/bramkarz/lib/main.dart":{"type":"remove"}}},"clientRequestTime":1718694229772}
1718694229772 => {"id":"104","method":"edit.getAssists","params":{"file":"file:///C:/Users/kkras/AppData/Local/Pub/Cache/git/dart-code-metrics-ab3c377449dc9a8d4f00376b338d7bd091e3eed5/lib/src/analyzer...
1718694229773 => {"id":"105","method":"analysis.getHover","params":{"file":"file:///C:/Users/kkras/AppData/Local/Pub/Cache/git/dart-code-metrics-ab3c377449dc9a8d4f00376b338d7bd091e3eed5/lib/src/analyz...
1718694229809 <= {"id":"102","result":{}}
1718694229809 <= {"id":"103","result":{}}
1718694229809 <= {"event":"server.status","params":{"analysis":{"isAnalyzing":true}}}
1718694229816 <= {"event":"analysis.errors","params":{"file":"file:///C:/Users/kkras/StudioProjects/bramkarz/lib/main.dart","errors":[]}}
1718694229817 <= {"event":"server.status","params":{"analysis":{"isAnalyzing":false}}}
1718694229832 => {"id":"106","method":"analysis.getHover","params":{"file":"file:///C:/Users/kkras/AppData/Local/Pub/Cache/git/dart-code-metrics-ab3c377449dc9a8d4f00376b338d7bd091e3eed5/lib/src/analyz...
1718694229836 <= {"event":"server.status","params":{"analysis":{"isAnalyzing":true}}}
1718694229847 => {"id":"107","method":"analysis.getHover","params":{"file":"file:///C:/Users/kkras/AppData/Local/Pub/Cache/git/dart-code-metrics-ab3c377449dc9a8d4f00376b338d7bd091e3eed5/lib/src/analyz...
1718694229862 <= {"id":"105","result":{"hovers":[{"offset":6708,"length":10,"elementDescription":"LintAnalysisConfig lintConfig","elementKind":"local variable","isDeprecated":false,"staticType":"LintA...
1718694229862 => {"id":"108","method":"analysis.getHover","params":{"file":"file:///C:/Users/kkras/AppData/Local/Pub/Cache/git/dart-code-metrics-ab3c377449dc9a8d4f00376b338d7bd091e3eed5/lib/src/analyz...
1718694229862 <= {"id":"106","result":{"hovers":[{"offset":2700,"length":8,"elementDescription":"String rootPath","elementKind":"local variable","isDeprecated":false,"staticType":"String"}]}}
1718694229862 => {"id":"109","method":"analysis.getHover","params":{"file":"file:///C:/Users/kkras/AppData/Local/Pub/Cache/git/dart-code-metrics-ab3c377449dc9a8d4f00376b338d7bd091e3eed5/lib/src/analyz...
1718694229874 <= {"event":"analysis.highlights","params":{"file":"file:///C:/Users/kkras/AppData/Local/Pub/Cache/git/dart-code-metrics-ab3c377449dc9a8d4f00376b338d7bd091e3eed5/lib/src/analyzer_plugin/...
1718694229882 <= {"event":"analysis.navigation","params":{"file":"file:///C:/Users/kkras/AppData/Local/Pub/Cache/git/dart-code-metrics-ab3c377449dc9a8d4f00376b338d7bd091e3eed5/lib/src/analyzer_plugin/...
1718694229883 <= {"event":"analysis.closingLabels","params":{"file":"file:///C:/Users/kkras/AppData/Local/Pub/Cache/git/dart-code-metrics-ab3c377449dc9a8d4f00376b338d7bd091e3eed5/lib/src/analyzer_plug...
1718694229884 <= {"event":"analysis.outline","params":{"file":"file:///C:/Users/kkras/AppData/Local/Pub/Cache/git/dart-code-metrics-ab3c377449dc9a8d4f00376b338d7bd091e3eed5/lib/src/analyzer_plugin/ana...
1718694229884 <= {"event":"analysis.overrides","params":{"file":"file:///C:/Users/kkras/AppData/Local/Pub/Cache/git/dart-code-metrics-ab3c377449dc9a8d4f00376b338d7bd091e3eed5/lib/src/analyzer_plugin/a...
1718694229885 <= {"event":"flutter.outline","params":{"file":"file:///C:/Users/kkras/AppData/Local/Pub/Cache/git/dart-code-metrics-ab3c377449dc9a8d4f00376b338d7bd091e3eed5/lib/src/analyzer_plugin/anal...
1718694229886 <= {"id":"107","result":{"hovers":[{"offset":1586,"length":8,"elementDescription":"Folder? location","elementKind":"local variable","isDeprecated":false,"staticType":"Folder?"}]}}
1718694229889 <= {"event":"server.status","params":{"analysis":{"isAnalyzing":false}}}
1718694229889 <= {"event":"analysis.implemented","params":{"file":"file:///C:/Users/kkras/AppData/Local/Pub/Cache/git/dart-code-metrics-ab3c377449dc9a8d4f00376b338d7bd091e3eed5/lib/src/analyzer_plugin...
1718694229895 <= {"id":"108","result":{"hovers":[{"offset":7281,"length":6,"elementDescription":"List<AnalysisErrorFixes> result","elementKind":"local variable","isDeprecated":false,"staticType":"List...
1718694229896 <= {"id":"109","result":{"hovers":[{"offset":2812,"length":6,"elementDescription":"LintAnalysisConfig? config","elementKind":"local variable","isDeprecated":false,"staticType":"LintAnaly...
1718694229903 <= {"id":"104","result":{"assists":[]}}
1718694229949 <= {"id":"4","error":{"code":"SERVER_ERROR","message":"Invalid argument (uri): URI scheme 'c' is not supported. Allowed schemes are 'file', 'dart-macro+file'.: \"c:/Users/kkras/StudioPro...
1718694229954 <= {"id":"4","error":{"code":"SERVER_ERROR","message":"Invalid argument (uri): URI scheme 'c' is not supported. Allowed schemes are 'file', 'dart-macro+file'.: \"c:/Users/kkras/StudioPro...
```

</details>

**Comment by santitigaga** [comment]
@xVemu  hello can you try to use the latest release?

**Comment by xVemu** [comment]
Yep, it's working now. Thank you
